<?php

declare(strict_types=1);

namespace Aster\Infrastructure\Security;

use Aster\Domain\Exception\EncryptionException;

/**
 * AES-256-GCM field-level encryption for clinical text.
 *
 * FRS 11.2 designates three columns as encrypted: patients.allergies_encrypted,
 * clinical_notes.content_encrypted, diagnostic_orders.results_payload_encrypted.
 * All three go through this class - repositories never call openssl_* directly.
 *
 * GCM rather than CBC: it is authenticated encryption, so a decrypt() that
 * does not throw is proof the bytes were produced by this key and have not
 * been altered since - exactly the "never silently return corrupted data as
 * valid data" requirement in FRS 11.2. A CBC ciphertext can be flipped bit-
 * by-bit into a different-but-valid-looking plaintext with no signal that
 * anything happened; GCM's tag makes that computationally infeasible.
 *
 * The key comes from APP_KEY (Config::$appKey), base64-encoded 32 random
 * bytes, generated by bin/install.php and otherwise unused until now. It
 * never touches the database - only .env - so a database backup alone
 * cannot be decrypted.
 *
 * Stored format: "aes256gcm.v1." then base64(nonce[12] . tag[16] . ciphertext).
 * The "v1" segment is a key-version marker, not a cipher-mode marker - if
 * APP_KEY is ever rotated, a v2 prefix and a second key let old rows still
 * decrypt while new writes use the new key. There is no rotation mechanism
 * yet (out of the FRS's stated scope), but the format does not have to be
 * migrated later to add one.
 */
final readonly class Encryptor
{
    private const string CIPHER  = 'aes-256-gcm';
    private const string PREFIX  = 'aes256gcm.v1.';
    private const int KEY_BYTES   = 32;
    private const int NONCE_BYTES = 12;
    private const int TAG_BYTES   = 16;

    private string $key;

    /** @throws EncryptionException when APP_KEY is missing or malformed */
    public function __construct(string $appKeyBase64)
    {
        if (trim($appKeyBase64) === '') {
            throw EncryptionException::missingKey();
        }

        $decoded = base64_decode($appKeyBase64, strict: true);

        if ($decoded === false || strlen($decoded) !== self::KEY_BYTES) {
            throw EncryptionException::invalidKey();
        }

        $this->key = $decoded;
    }

    /** @throws EncryptionException on failure */
    public function encrypt(string $plaintext): string
    {
        $nonce = random_bytes(self::NONCE_BYTES);
        $tag   = '';

        $ciphertext = openssl_encrypt(
            $plaintext,
            self::CIPHER,
            $this->key,
            OPENSSL_RAW_DATA,
            $nonce,
            $tag,
            '',
            self::TAG_BYTES,
        );

        if ($ciphertext === false || strlen($tag) !== self::TAG_BYTES) {
            throw EncryptionException::encryptionFailed();
        }

        return self::PREFIX . base64_encode($nonce . $tag . $ciphertext);
    }

    /**
     * @throws EncryptionException when the value is malformed, was
     *                             encrypted under a different key, or has
     *                             been altered since encryption
     */
    public function decrypt(string $stored): string
    {
        if (!str_starts_with($stored, self::PREFIX)) {
            throw EncryptionException::malformedCiphertext();
        }

        $decoded = base64_decode(substr($stored, strlen(self::PREFIX)), strict: true);

        if ($decoded === false || strlen($decoded) < self::NONCE_BYTES + self::TAG_BYTES) {
            throw EncryptionException::malformedCiphertext();
        }

        $nonce      = substr($decoded, 0, self::NONCE_BYTES);
        $tag        = substr($decoded, self::NONCE_BYTES, self::TAG_BYTES);
        $ciphertext = substr($decoded, self::NONCE_BYTES + self::TAG_BYTES);

        $plaintext = openssl_decrypt(
            $ciphertext,
            self::CIPHER,
            $this->key,
            OPENSSL_RAW_DATA,
            $nonce,
            $tag,
        );

        // openssl_decrypt returns false when GCM's authentication tag does
        // not verify - wrong key, flipped bit, truncated value. This is the
        // one branch FRS 11.2 exists for: never hand back a plausible-
        // looking but wrong plaintext.
        if ($plaintext === false) {
            throw EncryptionException::tamperedOrCorrupted();
        }

        return $plaintext;
    }

    /** True when $stored looks like output from encrypt() - a format check only, not a decrypt attempt. */
    public function looksEncrypted(?string $stored): bool
    {
        return $stored !== null && str_starts_with($stored, self::PREFIX);
    }
}
