-- =====================================================================
--  003 - Master Patient Index & Encounters
-- =====================================================================
--  Introduces the patient as a real entity for the first time. Until now,
--  identity was denormalised onto appointments.patient_* (deliberately -
--  see schema.sql's own comment on the `users` table: "Patients are NOT
--  accounts; they book anonymously by phone/email, which keeps PHI
--  surface area minimal"). That remains true for anonymous booking; this
--  migration adds the record a REGISTERED patient's clinical and
--  financial history hangs off, without touching how public booking works.
--
--  Five tables:
--    number_sequences  - atomic, collision-safe ID generation (not part of
--                         the FRS's own tables, but required by it: PID,
--                         visit number and receipt number must each be
--                         "generated by a collision-safe mechanism" and
--                         must "not use a non-atomic read-and-increment
--                         operation" - see NumberSequence.php).
--    patients           - the MPI itself (FRS 5.2).
--    patient_accounts    - patient portal credentials (FRS 5.3).
--    ward_locations      - bed/room master data (FRS 5.4).
--    encounters          - the unified OPD/IPD/ER interaction (FRS 5.5).
--
--  Decisions applied (see the approved implementation plan):
--    - Primary keys are BIGINT UNSIGNED, matching every other table in
--      this schema (appointments, payments, doctors, users all are) -
--      the FRS's own field tables say INT UNSIGNED, but that is exactly
--      the kind of technical ambiguity the FRS's scope directive asks to
--      be resolved against existing convention rather than followed
--      literally against it.
--    - patients.email is VARCHAR(190), matching users.email in this same
--      schema, not the FRS's VARCHAR(128) - both columns hold the same
--      kind of value in the same application.
--    - patient_accounts.patient_id is UNIQUE. The FRS's own DDL omits
--      this, but FRS 5.3 explicitly requires "the system must ... not
--      silently create multiple active portal identities for one
--      patient" - a UNIQUE constraint is the smallest mechanism that
--      actually guarantees that under concurrent requests; an
--      application-level check alone cannot.
--    - encounters.appointment_id (nullable, UNIQUE) bridges to the
--      unchanged public booking flow: check-in resolves/creates the MPI
--      patient from the booking's phone and links the new encounter back
--      to the appointment it came from. A walk-in encounter has no
--      appointment and appointment_id is NULL. See EncounterService.
--    - patients gets deleted_at, matching the soft-delete convention
--      every other table in this schema already uses; the FRS does not
--      mention deletion at all.
-- =====================================================================

-- ---------------------------------------------------------------------
--  number_sequences - atomic per-scope counters.
--
--  INSERT ... ON DUPLICATE KEY UPDATE next_value = LAST_INSERT_ID(...)
--  is the standard MySQL/MariaDB idiom for a race-free get-and-increment:
--  the UPDATE and the read of the new value happen as one atomic
--  operation from the connection's point of view (LAST_INSERT_ID() after
--  an UPDATE returns the value assigned to it in THAT statement), so two
--  concurrent callers can never receive the same number. See
--  NumberSequence::next() for the PHP side of this.
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `number_sequences` (
  `scope`      VARCHAR(40) NOT NULL,
  `next_value` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`scope`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
--  patients - the Master Patient Index.
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `patients` (
  `id`                       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pid`                      VARCHAR(20)     NOT NULL,
  `national_id`              VARCHAR(64)     NULL,
  `first_name`               VARCHAR(64)     NOT NULL,
  `last_name`                VARCHAR(64)     NOT NULL,
  `date_of_birth`            DATE            NOT NULL,
  `gender`                   ENUM('male','female','other') NOT NULL,
  `phone_number`             VARCHAR(32)     NOT NULL,
  `email`                    VARCHAR(190)    NULL,
  `address`                  TEXT            NULL,
  `emergency_contact_name`   VARCHAR(128)    NULL,
  `emergency_contact_phone`  VARCHAR(32)     NULL,
  `blood_group`              ENUM('A+','A-','B+','B-','AB+','AB-','O+','O-') NULL,
  -- Encrypted JSON string (AES-256-GCM, see Infrastructure/Security/Encryptor.php).
  -- Never queried directly - a patient's allergy list is read back into
  -- PHP and decrypted, never filtered on in SQL.
  `allergies_encrypted`      TEXT            NULL,
  `created_at`               DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`               DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at`                DATETIME        NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_patients_pid` (`pid`),
  UNIQUE KEY `uq_patients_national_id` (`national_id`),
  KEY `idx_phone` (`phone_number`),
  KEY `idx_demographics` (`first_name`, `last_name`, `date_of_birth`),
  KEY `ix_patients_deleted` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
--  patient_accounts - patient portal credentials.
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `patient_accounts` (
  `id`             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `patient_id`     BIGINT UNSIGNED NOT NULL,
  `password_hash`  VARCHAR(255)    NOT NULL,
  `is_active`      TINYINT(1)      NOT NULL DEFAULT 1,
  `last_login_at`  DATETIME        NULL,
  `created_at`     DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  -- One portal identity per patient - see this file's header comment.
  UNIQUE KEY `uq_patient_accounts_patient` (`patient_id`),
  CONSTRAINT `fk_patient_accounts_patient` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
--  ward_locations - physical and transient location master data.
--
--  No patient FK here by design (FRS 5.4): a location's occupant is
--  represented through encounters.current_location_id, not the other
--  way round - a bed does not "belong" to a stay, a stay is "at" a bed.
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `ward_locations` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ward_name`    VARCHAR(64)     NOT NULL,
  `room_number`  VARCHAR(32)     NOT NULL,
  `bed_number`   VARCHAR(32)     NOT NULL,
  `is_transient` TINYINT(1)      NOT NULL DEFAULT 0,
  `is_occupied`  TINYINT(1)      NOT NULL DEFAULT 0,
  `daily_rate`   DECIMAL(10,2)   NOT NULL DEFAULT 0.00,
  `created_at`   DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`   DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ward_locations_bed` (`ward_name`, `room_number`, `bed_number`),
  KEY `ix_ward_locations_occupancy` (`is_transient`, `is_occupied`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
--  encounters - the unified OPD/IPD/ER interaction.
--
--  appointment_id bridges to the EXISTING, UNCHANGED public booking
--  flow: check-in resolves the MPI patient from the booking's phone and
--  creates an encounter linked back to it. NULL for a walk-in with no
--  prior booking. UNIQUE because one booking is checked in at most once.
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `encounters` (
  `id`                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `patient_visit_number`        VARCHAR(24)     NOT NULL,
  `patient_id`                  BIGINT UNSIGNED NOT NULL,
  `appointment_id`              BIGINT UNSIGNED NULL,
  `primary_physician_id`        BIGINT UNSIGNED NULL,
  `current_location_id`         BIGINT UNSIGNED NULL,
  `visit_type`                  ENUM('OPD','IPD','ER') NOT NULL,
  `status`                      ENUM('CHECKED_IN','IN_CONSULTATION','ADMITTED','DISCHARGED','WALK_OUT','LEFT_WITHOUT_BEING_SEEN')
                                 NOT NULL DEFAULT 'CHECKED_IN',
  `financial_clearance_status`  ENUM('PENDING','APPROVED','OVERRIDDEN') NOT NULL DEFAULT 'PENDING',
  `admitted_at`                 DATETIME        NULL,
  `discharged_at`                DATETIME        NULL,
  `created_by`                  BIGINT UNSIGNED NULL,
  `created_at`                  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_encounters_visit_number` (`patient_visit_number`),
  UNIQUE KEY `uq_encounters_appointment` (`appointment_id`),
  KEY `ix_encounters_patient` (`patient_id`),
  KEY `ix_encounters_status` (`status`),
  KEY `ix_encounters_location` (`current_location_id`),
  KEY `ix_encounters_physician` (`primary_physician_id`),
  CONSTRAINT `fk_encounters_patient` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_encounters_appointment` FOREIGN KEY (`appointment_id`) REFERENCES `appointments` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_encounters_physician` FOREIGN KEY (`primary_physician_id`) REFERENCES `users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_encounters_location` FOREIGN KEY (`current_location_id`) REFERENCES `ward_locations` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_encounters_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
